name: SX-Attribute
main: github.saukiya.sxattribute.SXAttribute
version: 1.3.1
author: 
- Saukiya
softdepend:
- HolographicDisplays
- PlaceholderAPI
- RPGInventory
- MythicMobs
- SX-Level
- Vault

commands:
   sxattribute:
      # 命令使用方法，当命令被错误使用时将显示这个
      usage: error! please reload this plugin
      # 可自行添加删除触发指令的条件
      aliases:
      - sx
permissions:
  sx-attribute.use:
    default: true
  sx-attribute.stats:
    default: true