name: SX-Attribute
main: github.saukiya.sxattribute.SXAttribute
version: 2.0.2
author: 
- Saukiya
softdepend:
- HolographicDisplays
- PlaceholderAPI
- RPGInventory
- MythicMobs
- SX-Level
- SkillAPI
- Vault

commands:
   sxattribute:
      usage: error! please reload this plugin
      aliases:
      - sx
permissions:
  sx-attribute.use:
    default: true
  sx-attribute.stats:
    default: true